### ISSUE TITLE
Possibility to specify a default fallback culture

### ISSUE THREAD

**Issue by janrhansen** [mattbrailsford/Vorto#12] opened 2015-06-22 15:46 UTC
I might be doing this the wrong way - but I have 7 languages specified, and I always want to default to english if a value isn't specified for culture X, so I have to do this all the time

var something = CurrentPage.HasVortoValue("field", "en-US") ? CurrentPage.GetVortoValue("field", "en-US") : "something else - maybe CurentPage.Name";

It would be very comfortable :o) if it was possible to specify "en-US" in web.config or if the "Primary language" dropdown could serve this purpose as well (right now it seem to be indicating which language to show the user as default). Is that possible? I find it tedious to write "en-US" all the time, so I suspect I'm just doing it plain wrong :o)

BR, Jan

**Comment by janrhansen** [comment] 2015-06-23 13:50
I tested a bit more - and I now understand that I should be using GetVortoValue("field", fallbackCultureName:"en-US") in order to actually fallback. Just specifying "en-US" will pick that particular value as it (probably) matches the "string" signature/type of parameter cultureName. 

Would you consider adding a web.config value that supports specifying a default fallback culture, so it isn't necessary to write it _everywhere_ :o)

Second, I think I've found a bug. If I have a tree-structure of nodes 
A
-- B
-- -- C

which all have e.g. "field" specified from the same master documenttype (think SEO description), and I set a value for A ("general value") I can get that out at B and C by calling
GetVortoValue("field", recursive:true)
Great! As I expect.

Now, I write a more detailed value at B ("specific value") and reload page C - and get "specific value" as expected. If I then delete the value at B, I would expect C to render "general value" (from A) again, but instead I get a blank value. It appears that an initially empty field is "null", whereas a field where I've deleted content is not "null" but rather String.empty, wich is what I get then. Could it be an error in the vorto wrapper that should set the saved value to null, but set it to string.empty? The datatype I'm wrapping is a textstring multiple.

BR, Jan

**Comment by griff158** [comment] 2015-07-01 13:44
Hi Jan,

Did you find a workaround for the recursive problem i seem to have the same problem.?
i believe that the issue is that when you empty a VortoValue property the property is not removed as with 'normal' properties but the is filled for example with:

 <titletag> <![CDATA[{"values":{"en":"","nl":""},"dtdGuid":"c8255676-764e-4f0a-afe8-bafbe53d1ead"}]] </titletag>

So umbraco recursive the value is found but it's an empty VortoValue.

**Comment by mattbrailsford** [comment] 2015-11-28 18:08
@janrhansen I think this recursive issue should now be fixed in commit c3afa58ee6e59c1dedcbf10bf7a9f18da8941417 I've changed how recursive works here so it now iterates over each ancestor, checking the property AND looking for a value for a given culture, rather than before, just looking for a vorto value for the property.

**Closed by mattbrailsford** 2015-11-28 18:08 UTC
