### ISSUE TITLE
Vorto should use ConvertSourceToObject instead of ConvertDataToSource

### ISSUE THREAD

**Issue by jbreuer** [mattbrailsford/Vorto#19] opened 2015-08-25 12:28 UTC
More info: https://our.umbraco.org/projects/developer-tools/umbraco-core-property-value-converters/feedback/69249-problem-with-multiple-media-picker-inside-vorto-and-value-converter#comment-227870

**Comment by mattbrailsford** [comment] 2015-11-26 19:35
I've created what I think is the right fix here, would you be able to test it?

https://github.com/mattbrailsford/Vorto/tree/bug/convert-source-to-object

**Comment by jbreuer** [comment] 2015-11-27 12:39
Sorry didn't have time to test it yet, but the code looks similar to a fix I once made for Archetype so I think this should work :-) https://github.com/imulus/Archetype/commit/07750c75371d04dc00efa28c77f6c18c89f43b7e

**Comment by mattbrailsford** [comment] 2015-11-28 16:30
Fixed in commit ea5789d78da1f1e0af11cc6c688a5e188650bb1d

**Closed by mattbrailsford** 2015-11-28 16:30 UTC

**Comment by mattbrailsford** [comment] 2016-03-27 15:53
Just thought I'd write a note hear as this fix has been somewhat reversed in the upcoming release as I've now remembered whilst helping someone else fix an issue why ConvertDataToSource is tried first. The reason is that the editor value is saved as JSON rather than as XML if it was a normal property. The problem is, during the conversion to XML ConvertDataToSource is called, however because our value is stored as JSON, it never is, so we have to have code that runs ConvertDataToSource first, and if the value still isn't correct, then it tries ConvertSourceToObject.

**Comment by mattbrailsford** [comment] 2016-03-27 15:56
Just to note, both methods are still tried, so things should still work as before, it's the fact code was changed to try ConvertSourceToObject first that has been reverted so that ConvertDataToSource is tried first.
